### ISSUE TITLE
Changing license for GPL 2 compatibility

### ISSUE THREAD

**Issue by tardyp** [tavendo/AutobahnPython#326]
Hello,

I'm considering wamp as a protocol for websocket for use in buildbot ui.

We dont want to require people installing buildbot to install the whole crossbar.io, but we are still interested in using wamp (and angular-wamp) as a higher level api to websocket (instead of writing our own).

So I'm wondering if this usecase is still supported by autobahn with the recent move of the router outside to crossbar.io.

**Comment by goeddea** [comment]
First of all: Cool that you want to use WAMP for buildbot!

Regarding your question: Not sure I get this right.

- AutobahnPython no longer has a router. If you want a Python router you need to use Crossbar.io.

- Installing "the whole crossbar.io" is not a big deal regarding space requirements. It also installs via easy_install/pip, same as buildbot.

- From the buildbot documentation, buildbot currently shares the limitation which the move of the basic router from Autobahn|Python to Crossbar.io introduced, i.e. only running on Python 2.x because of the requirement for Twisted.

So I'm wondering what exactly the problem with installing Crossbar.io as part of the buildbot install process is?

(Also: This is really more of a question for the mailing list than an issue.)

**Comment by tardyp** [comment]
Sorry for spamming your issue. I was not sure whether you had a mailing list. I saw that your IRC was not very active.

I'm okay to depend on crossbar and autobahn, but my concern is that buildbot is already hard enough to setup. Adding another process and port to install, route and maintain sounds too much for a CI system. Completly switch buildbot to become a crossbar.io application looks a bit scary for now :)

So I'd prefer the wamp router just sits in my $buildbotURL/ws 

By digging into the source, I created a PoC that works.
https://github.com/tardyp/buildbot/commit/5a4bebb57f5d6a5411bb4472b7f41a277dcf94a2

My concern is: are those api supported?
The actual wamp server part is here:
https://github.com/tardyp/buildbot/blob/5a4bebb57f5d6a5411bb4472b7f41a277dcf94a2/master/buildbot/www/wamp.py

**Comment by oberstet** [comment]
Hi Pierre,

no, there is no Python level API supported by Crossbar.io - deriving from Crossbar.io Python classes means your code might break on any subrelease. The API supported is purely WAMP for both apps and management plus config files and such. Imagine we rewrite Crossbar.io in C++ (no plans to do so, but for illustration). Also note that Crossbar.io is under AGPL  3.0 - I don't know if that is compatible with GPL 2.

Crossbar.io should be looked at likea black box ... like Apache or RabbitMQ. And we will have proper installers soon .. RPMs /DEBs etc soon. These will be completely self contained bundling their own Python and everything. So installation will be a snap ..

Am 05.02.2015 15:20 schrieb Pierre Tardy <notifications@github.com>:

Sorry for spamming your issue. I was not sure whether you had a mailing list. I saw that your IRC was not very active.

I'm okay to depend on crossbar and autobahn, but my concern is that buildbot is already hard enough to setup. Adding another process and port to install, route and maintain sounds too much for a CI system. Completly switch buildbot to become a crossbar.io application looks a bit scary for now :)

So I'd prefer the wamp router just sits in my $buildbotURL/ws

By digging into the source, I created a PoC that works.
tardyp/buildbot@5a4bebb<https://github.com/tardyp/buildbot/commit/5a4bebb57f5d6a5411bb4472b7f41a277dcf94a2>

My concern is: are those api supported?
The actual wamp server part is here:
https://github.com/tardyp/buildbot/blob/5a4bebb57f5d6a5411bb4472b7f41a277dcf94a2/master/buildbot/www/wamp.py

**Comment by tardyp** [comment]
Le Thu Feb 05 2015 at 4:58:27 PM, Tobias Oberstein <notifications@github.com>
a écrit :

> Hi Pierre,
>
> no, there is no Python level API supported by Crossbar.io - deriving from
> Crossbar.io Python classes means your code might break on any subrelease.

Ok I understand that.

> The API supported is purely WAMP for both apps and management plus config
> files and such. Imagine we rewrite Crossbar.io in C++ (no plans to do so,
> but for illustration). Also note that Crossbar.io is under AGPL 3.0 - I
> don't know if that is compatible with GPL 2.
>
Indeed, that part is also annoying. There is still the possibility to
unbury the gpl2 code from 0.9.5, and make a separate package.


Crossbar.io should be looked at likea black box ... like Apache or
> RabbitMQ. And we will have proper installers soon .. RPMs /DEBs etc soon.
> These will be completely self contained bundling their own Python and
> everything. So installation will be a snap ..
>

Well that is still a problem for me. Some of the drawback I can see:
Have to setup a separate scheme for authentication / authorization.
Prevents us to have buldbot be a pure 12 factor app deployable instantly
with cloud foundry or deis.
Cross domain issues, related to authentication.

I mean crossbar looks awesome for complex IOT applications and other, but
wamp also looks very good technology for simpler use-cases.

**Comment by tardyp** [comment]
>
>  Also note that Crossbar.io is under AGPL 3.0 - I don't know if that is
>> compatible with GPL 2.
>>
> Indeed, that part is also annoying. There is still the possibility to
> unbury the gpl2 code from 0.9.5, and make a separate package.
>

My bad. autobahn is Apache v2. Which makes it incompatible with the GPL v2
of buildbot :-(

So. No luck for us. No wamp

**Comment by oberstet** [comment]
Rgd. authentication and authorization: Crossbar.io allows you to write custom AA as regular WAMP components and plug that in. https://github.com/crossbario/crossbar/wiki/WAMP-CRA-Authentication#dynamic-credentials

There is no need to hack the router or Crossbar.io for AA.

Rgd. AutobahnXXX license: yep, this is Apache 2.0. The FSF thinks it is incompatible with GPL 2. The GPL 3 is compatible with Apache 2.0. As far as I can see, buildbot is GPL version 2 - and only 2 (not 2 or later). So yes, this is a problem - you can't use Autobahn code in buildbot - even not the old code that still had a basic router embedded.

*If* you really want to use WAMP, Autobahn, Crossbar.io, we *might* think about changing the license for AutobahnPython or dual-license - which is a total pain since it requires to contact all contributors.

**Comment by tardyp** [comment]
After thinking more about it, I really think wamp is solving a lot of problems for us.
Crossbar might even be solving some of our scalability problems, but we'll have to really dig into the details. I'm concern about the crossbar server to be a bottleneck if 2000 slaves are sending their build logs via pub sub. I'll post my analysis on you ml when my ideas are more clear.

autobahn + crossbar.io could solve our problem of:
- mq backend  -> we were planing on using amqp + kombu
- slave master protocol -> we were planning on using twisted amp
- web ui realtime protocol -> need to do our own proto, as there is nothing out of wamp for twisted.

I think it might be less time for us to even help you and drive the switch rather than code all those solutions.

I have been following the switch for bootstrap css lib: https://github.com/twbs/bootstrap/issues/2054. One comment of the bug points to a tool to help in the process of gather developer sign in. https://github.com/beberlei/license-manager

I myself is not very found of GPLv2, but for us the change would be nightmare
git log |grep Author |sort | uniq -c |sort -n |wc -l
506
while autobahnPython is:
git log |grep Author |sort | uniq -c |sort -n |wc -l
34

**Comment by oberstet** [comment]
Changing the license of AutobahnPython sucks, but should be doable, and is definitely easier than changing buildbot license. We are in close contact to all of those that contributed most (https://github.com/tavendo/AutobahnPython/graphs/contributors). Well, and me I am in contact with myself;)

Let me know if you have questions rgd architecture etc. and if you would go with WAMP etc if we change license ..

Regarding performance, here are some numbers for the old basic router in AutobahnPython (Crossbar.io will behave similar): http://tavendo.com/blog/post/autobahn-pi-benchmark/

Also, we have clustering/federation on the roadmap. This will take some time to arrive though yet.

**Comment by oberstet** [comment]
@tardyp Ok, have been discussing this internally a bit. Since it's a lot of work (contacting contributors .. and probably even ripping out / rewriting code if we don't get agreements) and will take time: do you have a rough estimate on the chances of Buildbot using this stuff? Is it more like 50% or "still evaluating - dunno" stage?

**Comment by tardyp** [comment]
For me this is a 80% chance. I've been delayed a little bit today by my assumption that wildcard matching was implemented, but beyond that,, my PoC is going very fast, and I am pretty happy with autobahn/crossbar.

Also, switching to MIT will help autobahn to be used by other GPLv2 projects.

The bootstrap switch took time, but they got a lot more contributors, and they eventually did rewrite very few code. As MIT and apache are really similar, people usually don't bother.

Like I said, as this will save me a lot of time, I'm volunteering to do the tracking job. I'd prefer you work on wildcard matching :)

**Comment by oberstet** [comment]
I guess you are right about MIT helping us in general (even if Buildbot chose something else). With AutobahnJS, we did the switch long ago. With AutobahnCpp, it's much easier (I wrote nearly all the code https://github.com/tavendo/AutobahnCpp/graphs/contributors). With AutobahnAndroid, it's more work again.

If you organize the contacting of contributors etc for AutobahnPython, that would be awesome! I promise to get pattern based subs into Crossbar.io until coming saturday.

**Comment by tardyp** [comment]
Hey,
To do my part of the deal, I created a script who can send email to all contributors. I've run it for @tavendo.de people, so you should have received it. Please let me know if you agree with the phrasing and I'll send that to everybody.

**Comment by goeddea** [comment]
Thanks for managing the switch! I just approved the switch for whatever my contributions where.

Regarding the email text,  I suggest some modifications:

-------
You are getting this mail, because you are a contributor to AutobahnPython. The project now wants to switch its open-source license from [Apache 2.0]() to [MIT]().

The MIT license is more liberal than Apache, and allows the wider use of AutobahnPython. 

As a current example, Apache 2.0 makes use of AutobahnPython with GPL v2 projects difficult to impossible, see http://www.apache.org/licenses/GPL-compatibility.html. This is affecting the planned use of AutobahnPython in [Buildbot](http://buildbot.net/), a use which we're excited about.

Please visit the following link where you can approve or disapprove the change of license for your contributed code:
-----

I think it makes sense to give a more detailed reasoning for the trigger of the switch and for the benefits, without them having to read the Apache foundation post. 
Plus I think that telling people about Buildbot (if that is OK with you) makes it clear that there is some actual necessity for the switch.

That's my 2 cents. I think we should wait for Tobias' feedback (he should be in the office a bit later today).

**Comment by oberstet** [comment]
@tardyp cool! I've approved the change from my side. I agree with @goeddea about the slight additions to the text: it is nice to let contributors know that there is a concrete case for this (possible use in buildbot).

**Comment by tardyp** [comment]
all emails have now been sent with your modifications

**Comment by oberstet** [comment]
Awesome! I hope we get feedback of all contributors soon. Btw: I am working on pattern subs ..

Am 14.02.2015 16:04 schrieb Pierre Tardy <notifications@github.com>:

all emails have now been sent with your modifications

**Comment by oberstet** [comment]
@tardyp alright, prefix- and wildcard-matching subscriptions are now implemented in Crossbar.io trunk.

It needs a little more polish and testing before release, but it works:

* https://github.com/tavendo/AutobahnJS/blob/master/package/test/test_pubsub_prefix_sub.js
* https://github.com/tavendo/AutobahnJS/blob/master/package/test/test_pubsub_wildcard_sub.js

I've also implemented WAMP meta events and procedures for PubSub .. undocumented and experimental. Will write about it ..

**Comment by tardyp** [comment]
I sent a reminder mail today, and we got a batch of new buy-in.

**Comment by remyroy** [comment]
I agree with the license change.

**Comment by oberstet** [comment]
Alright. We've got acknowledge for the license change from all but 2 users.

* https://github.com/tavendo/AutobahnPython/commits?author=cachedout
=> These changes were trivial, and apply to example code (not library) and those examples were for WAMP1 and the code isn't there any more anyway.

* https://github.com/tavendo/AutobahnPython/commits?author=flyser
=> trivial changes (typos, docstrings or log messages)

* https://github.com/tavendo/AutobahnPython/commits?author=the-user-shmuser
=> trivial (1 liner, important though)

====

I'd say this is sufficient for the license change to happen. I will do that now (want to move on).

**Comment by oberstet** [comment]
@remyroy thanks!
@tardyp alright. done! https://pypi.python.org/pypi/autobahn/0.10.0
