### ISSUE TITLE
Being unable to connect to the router should log an error

### ISSUE THREAD

**Issue by sametmax** [tavendo/AutobahnPython#328]
Right now, if a client can't connect to a router, it just hangs. You need to put print() in the code run "on join" and assume that, if the print() doesn't appear, it's because connection failed. 

Printing a line after some time saying you can't connect to the router would help.

**Comment by oberstet** [comment]
need to check if this is still the case after the many improvements to error handling and logging

**Comment by meejah** [comment]
For illegal realms and un-found URLs I can confirm it now (after #464) produces some better logging on the server-side (for router components). Also, any case of "failed handshake" should print out the actual reason now, instead of just an aborted connection.

However, I'm not sure what happens if e.g. the host/IP or port is wrong. It might also be useful to point out in the docs that overriding ``onLeave`` to print out the details arg can be useful (I did already change the default implementation in #464 to print the message out if it's a ``wamp.error.*`` reason).

**Comment by meejah** [comment]
If the IP/address is wrong, a timeout is triggered (and logged). If just the URL (path) is wrong, then a 404 happens (and is now logged properly in the server). In both cases, crossbar shuts down.
