### ISSUE TITLE
Fake Calls to oneself

### ISSUE THREAD

**Issue by Paranaix** [tavendo/AutobahnPython#333]
If one wants to call a endpoint registered by oneself, such a call shouldn't result in an actual CALL message being sent over the wire but a regular python call should be invoked.

Of course calling the endpoint directly (via Python) would also be possible but that creates problems if later on parts get moved to different applications (/peers). Also things like progressive results wont work.

The implementation should behave exactly like a real wamp call would but without any actual traffic / overhead.

**Comment by oberstet** [comment]
No, it should go over a transport via the router.

Reasons: for tracking, for permissions checking, for behaving exactly the same when the component is moved etc.

Correctness is more important than saving a network roundtrip.

**Comment by oberstet** [comment]
Actually, when you run a Python component side-by-side with a router in Crossbar.io, nothing is serialized effectively - however, there is still a fake transport in place: which you is indeed function-call based.

In any case, since the routing code now resides in Crossbar.io, this issue should live there - but it is already implemented for side-by-side components - hence closing.
