### ISSUE TITLE
Support passing arbitrary options in {Register, Call, Subscribe, Publish}Options

### ISSUE THREAD

**Issue by bb4242** [tavendo/AutobahnPython#366]
The WAMP protocol is explicitly designed to be extensible by populating `Options|dict` arguments in the `REGISTER`, `CALL`, `SUBSCRIBE`, and `PUBLISH` messages (see [here](https://github.com/tavendo/WAMP/blob/master/spec/basic.md#message-definitions)).  There are many interesting use cases for these options.  To mention just one example, they could be used in the `SUBSCRIBE` message to perform rate limiting of messages that the broker sends to the client.

The current autobahnPython library, however, does not expose the ability to set arbitrary options.  Rather, the relevant options classes, `RegisterOptions`, `CallOptions`, `SubscribeOptions`, and `PublishOptions`, only allow the user to speficy a small, pre-defined set of options.  For example, `RegisterOptions` only accepts the `invoke` and `details_arg` options.

It would be very useful to allow the options classes to pass through arbitrary options, so that clients and servers could extend the base WAMP functionality if necessary for the application.

If there is agreement that this would be useful, I'm happy to put together a pull request to implement this proposal.

**Comment by oberstet** [comment]
No. These options/details are WAMP protocol / library internal, and not exposed at user level.

**Comment by bb4242** [comment]
Well, I guess my point is that some options/details **are** exposed at user level, but only the ones that AutobahnPython has decided are relevant.  In my application, I'm writing a custom WAMP broker/dealer that would ideally like to accept options other than the AutobahnPython-supported ones in order to extend the basic WAMP semantics in some areas.  My understanding was that WAMP was designed to be extended in this way, and it would be nice if the WAMP clients allowed access to that extensibility.

**Comment by bb4242** [comment]
PS - Thanks for the quick reply! :)

**Comment by oberstet** [comment]
@bb4242 Yes, WAMP is designed for extensibility (see the advanced spec and the ongoing work there), but not at the *user* level. And it is not AutobahnPython deciding, but the WAMP spec. We want interoperability, and if every implementation comes up with it's own thing, then that doesn't work. If you "extend the basic WAMP semantics", great, but please don't call it WAMP then ...

**Comment by mtourne** [comment]
To me it might make sense to expose some of that at the "user level" to provide more extensibility in the way a wamp broker is devised. 
It could enable the "user" (the one who implements a broker here, in contrast to the Authoban user) to make a wamp compatible service with a different set of "advanced options" offered by the broker, outside of the ones of the "official ones"™ (because no one thought that should be standardized). While still using the official client.

The same way different HTTP servers will use different sets of headers while still staying compatible with a standard http client. Proxies for instance issue the almost-standard X-Forwarded-For.

In general, 
It seems like there is value for a protocol in letting the user-implementer add custom meta-information instead of channeling everything in the payload fields.

**Comment by oberstet** [comment]
@mtourne Actually, the protocol spec allows such custom, non-standard keys in options/details dicts: https://github.com/tavendo/WAMP/blob/master/spec/basic.md#messages => "Extensibility"

The spec also says: "Attributes unknown to an implementation MUST be ignored."

"ignored": an implementation should not bail out, but simply treat the same as if it wouldn't exist.

Maybe I misunderstood the question: who is _user_? An implementor of WAMP (client library or router) or an actual WAMP application developer?

**Comment by bb4242** [comment]
Perhaps I can clarifiy: as a WAMP application developer, using the AutobahnPython library, I'd like to do something like this:
```
def onJoin(self, details):
    self.subscribe(myHandler, 'test.myTopic', options=SubscribeOptions(rateLimit=True))
```
This would have the effect of adding a `{'rateLimit': True}` entry to the WAMP `SUBSCRIBE.Options` parameter that gets sent over the wire to the server.  As you said, if the server is a stock server that doesn't understand this option, it should simply ignore it.  But if the server understands this option, it can react accordingly.

**Comment by Paranaix** [comment]
I kind of sympathize with this issue. For an user its fatal, if a required feature is not available in the standard and there is no way to implement it on your own besides forking from the original poject. On the other hand I understand if @oberstet fears that allowing arbitrary option/parameters diverges WAMP implementations. However I believe thats a general issue with standards: (fast) progress vs intercompatibility.

IMO we should allow arbitrary options. Simply because its fatal if such a thing blocks development. However it should explcitly noted in the documentaton, that yonder feature is not to be exploited by custom WAMP implementations. Instead custom WAMP implementors should participate in the development of the standard if they want to implement a new feature which they deem lacking.

**Comment by daviddking** [comment]
@oberstet, I think you're reading too much into the specification (https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02). The spec defines the network protocol, it does not define what is an appropriate to expose in an API. Subscription options are are a valid part of the network protocol and can provide "provide additional subscription request details in a extensible way". There is no reason not to include them in the Python API. They are exposed in the Autobahn JS API and we've found them incredibly useful mechanism to include parameters in topic subscriptions. The only alternative would be to embed topic parameters in the topic name itself. As it is, without having parity with Autobahn JS, the Python API will alienate a group of users who would otherwise find it incredibly useful.

**Comment by daviddking** [comment]
@oberstet , Are you an author of the spec? I will add another vote for provide support in the specification and in the standard APIs for application-defined subscription options. Autobahn JS supports this and as the author of a sizeable enterprise WAMP application developed over the past two years I can tell you that we have used them to great effect. Not having parity with Autobahn JS alienates Python developers that would otherwise find the API incredibly useful.

**Comment by oberstet** [comment]
>  Autobahn JS support

No, it doesn't.

**Comment by daviddking** [comment]
Example Autobahn JS code:

`session.subscribe('kcg.risk.SignalsByPortfolioIdAndContract', onevent, {
					"sessionId": '2431d7b4-6605-4a5c-b6f3-d544ca845329',
					"contractId": 1743395,
					"portfolioIds": [23898]
				});`

A possible workaround for Autobahn Python might be to encode parameters in the topic URI:

`yield self.subscribe(onEvent, u'kcg.risk.SignalsByPortfolioIdAndContract?sessionId=2431d7b4-6605-4a5c-b6f3-d544ca845329&contractId=1743395&portfolioIds=[23989]')`

From an API perspective, though, having the ability to pass a dictionary of options rather than encoding parameters in the topic URI feels much cleaner.

**Comment by oberstet** [comment]
Above is misuse of the library and not supported by the WAMP protocol spec. Best probably will be to add checking code in AutobahnJS to avoid users falling into this trap ..

**Comment by daviddking** [comment]
@oberstet - If I understand you, the WAMP specification is purely a network protocol specification, not an API specification and although the options parameter is a guaranteed part of the protocol, the intent is to support only specific options that are called out in the current specification (but allow for future versions of the specification to specify additional parameters), specifically the router is not required to forward parameters it doesn't recognize making it unusable for the purpose of passing application-specific options. If you could clarify this in the spec, that would be great - I implemented a Java router based on an earlier version of the spec and it wasn't clear to me at all. In fact, subscription options ended up being a heavily used feature in my implementation. As for what to do with Autobahn JS - I don't know - if you added enforcement of a restricted set of keys in the client you could break a lot of existing code.

Passing parameters in the topic URI is probably sufficient. If that is the recommended approach, it would be great if (a) there were examples of this in the standard example set, and (b) support for encoding and decoding URI parameters in the APIs.
