### ISSUE TITLE
Some files are missing license headers

### ISSUE THREAD

**Issue by FlaPer87** [tavendo/AutobahnPython#386]
Hi,

We're using autobahn in the `openstack/zaqar` project and we're at the point where we need to start creating packages for it. In order to do so, we also need to create a package for autobahn since it's a dependency. However, debian/ubuntu packagers have raised an issue with regards to some files not having a license. Without this license, it's not possible to package Autobahn.

The files causing problems are:

```
P: python-autobahn source: source-contains-prebuilt-javascript-object examples/twisted/websocket/echo_wsfallbacks/web/swfobject.js mean line length is about 10071 characters
E: python-autobahn source: source-is-missing examples/twisted/websocket/echo_wsfallbacks/web/swfobject.js
P: python-autobahn source: source-contains-prebuilt-flash-object examples/twisted/websocket/echo_wsfallbacks/web/WebSocketMain.swf
E: python-autobahn source: source-is-missing examples/twisted/websocket/echo_wsfallbacks/web/WebSocketMain.swf
P: python-autobahn source: source-contains-prebuilt-javascript-object examples/twisted/wamp/authentication/ticket/autobahn.min.js
E: python-autobahn source: source-is-missing examples/twisted/wamp/authentication/ticket/autobahn.min.js
P: python-autobahn source: source-contains-prebuilt-javascript-object examples/twisted/wamp/authentication/otp/autobahn.min.js
E: python-autobahn source: source-is-missing examples/twisted/wamp/authentication/otp/autobahn.min.js
P: python-autobahn source: source-contains-prebuilt-javascript-object examples/twisted/wamp/app/serial2ws/autobahn.min.js
E: python-autobahn source: source-is-missing examples/twisted/wamp/app/serial2ws/autobahn.min.js
P: python-autobahn source: source-contains-prebuilt-javascript-object examples/twisted/wamp/app/hello/autobahn.min.js
E: python-autobahn source: source-is-missing examples/twisted/wamp/app/hello/autobahn.min.js
```

**Comment by oberstet** [comment]
Distros should package the AutobahnPython _library_ only, not the docs, and not the examples.

The files you mention above:

* autobahn.min.js => different project (AutobahnJS)
* WebSocketMain.swf => Flash bytecode .. can't have a copyright notice
* swfobject.js => different project (WebSocket Flash implementation)

**Comment by thomasgoirand** [comment]
Oberstet, I'm the person doing the actual packaging in Debian.

Whatever I do, your source files are there, and part of your original source code. And we do upload to Debian all including source code. So autobahn.min.js really is there in a minified form, and should be replaced by a non-minified version, same for swfobject.js. And the .swf object can't even be dealt with.

So, please, if you want this not packaged, then you should remove it from your original tarball and git repository, evenutally pushing them in a separate non-free Git repo.

**Comment by oberstet** [comment]
> And we do upload to Debian all including source code.

Then the packaging is broken. If you want to look at some packaging done right, here you go (FreeBSD):

* http://www.freshports.org/www/py-autobahn/
* https://svnweb.freebsd.org/ports/head/www/py-autobahn/

**Comment by oberstet** [comment]
FWIW, we also provide complete, packaged binaries for Crossbar.io (which includes AutobahnPython), bundling everything (including a working, latest PyPy) here http://crossbar.io/docs/Installation-on-Ubuntu/

**Comment by thomasgoirand** [comment]
Man, you're basically saying that the packaging is broken because we require everything to be free software. Of course, I can remove the files manually, but that's some burden that you are adding on me, and on all other distribution (Red Hat and other distro have the same requirements).

**Comment by oberstet** [comment]
@thomasgoirand no, what I am saying is: don't blindly tar up everything in a repo to get a "package". why would some distro specific packaging rules impose restrictions on how we structure our repo? and the next distro imposes different rules. doesn't make sense. also: everything in that repo is open-source software.

> but that's some burden that you are adding on me, 

Yes, correct. Upstream should not have additional burden due to distro specific packaging mechanisms.

**Comment by FlaPer87** [comment]
@oberstet that's one way to put it.

The other way we could put this request is that it'd be nice for Autobahn to be structured in a way that would also *help* other distributions. It's not about *imposing*. These are package formats that have been around for ages. Are they perfect? Certainly not, but they are there and changing them is very unlike.

As a project maintainer, I want my project to play nice with the ecosystem around it and its consumers. It will never be possible to make everyone happy but I wouldn't say these kind of requests are impositions but rather the community consuming your software giving back to you based on the experiences it has had.

The only thing that this issue is trying to achieve is to make it easier for autobahn to be distributed. 

Thanks

**Comment by meejah** [comment]
What would it take to fix the issue here? Is it just that the autobahn.min.js files need a copyright header? I don't see how the .swf files can be "fixed"...? (I'm currently fixing up some of the examples etc in Autobahn, is why I'm asking).

@oberstet: a lot of Debian packages do include docs or examples, e.g. in /usr/share/doc/package-name/examples/* etc. which can be nice (so, e.g., experienced Debian users then don't have to "git clone" to get the Autobahn examples).

**Comment by oberstet** [comment]
@meejah Yeah, while cleaning up the examples, probably we should simply remove all the `autobahn.min.js` files and instead link `<script src="http://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz"></script>`.

Rgd. the OPs concrete issues: that leaves us with the 2 files from https://github.com/gimite/web-socket-js Probably it works if we link to the GH raw blobs for these in the example HTML?

**Comment by oberstet** [comment]
actually, we should use (pls note the http**s**):

```html
<script src="https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz"></script>
```

**Comment by meejah** [comment]
Hmmm, interesting. I'll try that, hopefully GH gets the mime-type right..

@thomasgoirand that will work for Debian, right? It's the flash-blobs and re-distributed .js files that are the problem?

**Comment by oberstet** [comment]
@meejah One more thing as you go over the examples: with the library itself, we've gone through that license change thing (Apache 2.0 -> MIT) and the Flake8/PEP8 dance to make the buildbot (GPL2) guys happy;) Which was nice, as I really think it's "better now".

The examples still have Apache 2.0 and probably aren't PEP8.

Not sure, but I guess I have written nearly all (all?) the examples (other than smallish PRs). Would it make sense to use MIT also? I'd support that. And to either cull examples radically (please do! in particular the WAMP ones) or make them fully PEP8?

**Comment by meejah** [comment]
I wil pep8/flake8 all the examples and make sure they have MIT headers; I think it makes sense to keep the license consistent (probably also a packaging-problem, I suspect?). I believe I ran pep8 at least on all the "basic" ones I did before...

**Comment by oberstet** [comment]
@meejah awesome!! it totally makes sense.

**Comment by oberstet** [comment]
On a sidenote, I always wonder why AutobahnPython and AutobahnJS seem to be treated differently rgd distro packaging.

Consider:

```console
mkdir ~/test
cd test
npm install autobahn
```

Installs AutobahnJS into local app dir `~/test` from NPM.

```console
virtualenv ~/test
~/test/bin/activate
pip install autobahn
```

Installs AutobahnPython into local app dir `~/test` from PyPI.

Similar commands will install Autobahn into the "system run-time".

Nevertheless this similarity (run-time specific repos exist with NPM and PyPI), somehow AutobahnPython is expected to be distro-packaged, while AutobahnJS is not. Strange ..

**Comment by thomasgoirand** [comment]
@oberstet 

What you are proposing to do is to replace a minified file (which is considered non-free by most distribution including Debian and Red Hat) by a privacy breach. What I mean by that is that anyone having the control of autobahn.s3.amazonaws.com (be it yourself, or an AWS admin, or the NSA...) knows many things about the useage of the web page, or even can replace the content of the javascript file by who knows what. This is even worse. If you were to do that, it would have the same result: I'd be force to remove the examples folder from the orig.tar file.

I'm not sure if you understand well where I am here. I'm trying to package your software the best way possible, and include all examples, as I think they are very valuable to Debian users. Replacing a minified file by its source-full counterpart isn't hard, and will please anyone. I'm convince no-one cares much about having browser optimized content for what's in the examples folder.

As for the flash file, indeed, there's no way to fix this, because we currently don't have any free software flash compiler around. So there's no way but removing the file entirely. If you don't want to do that (which I would perfer not, but which I can understand), then just do the replacement of the minified files, and I'll take care of removing the flash object myself from what I will upload to Debian. That's more work, but that's preferable than just removing all examples, don't you think?

By the way, I wanted to let you know that these aren't rules that I am inventing. If these issue aren't fixed, and I try to upload the package, it will be simply rejected the FTP masters who are doing a peer review on each new package. These are established rules inside Debian (and other distro) which it is impossible to change (and which by the way I agree with, but I don't think my opinion has any importance in this case).

Hoping I've been more convincing and used nicer wording in this last post, cheers,

Thomas Goirand (zigo)

**Comment by thomasgoirand** [comment]
Oh, by the way, if you think AutobahnJS would be better packaged in Debian, I can agree to do it, if you think this has value for this Python package. Maybe you could share some light with me about it? How do they interact with each other?

Oh, and about the licensing, I'd be happy if you could explain which part is using what license, because all of that information needs to be gathered and written in the debian/copyright file. And if it's done wrongly, there's a lot of chances that the package would be rejected by the FTP masters. The worst possible situation would be no licensing information at all upstream (and if you use some license, make sure you include the full text of it, as it is sometimes required by the license itself like for example the MIT license...). Hoping this helps...

Cheers,

Thomas

**Comment by oberstet** [comment]
@thomasgoirand Thanks for your detailed explanation! I guess we'll stick to using links in the HTML examples to Web resources, as this provides the best developer experience and maintainability for us. It's kinda expected for Web developers.

Consequently, I really think the best approach is to only package up the AutobahnPython library, which means everything but the docs and examples directories. The docs are online at http://autobahn.ws/python, and the examples are here on GitHub for anyone (this is also where we link to in the docs btw). The license file for the library is here https://github.com/tavendo/AutobahnPython/blob/master/LICENSE

> The examples currently still use the Apache 2.0 license. We will change that to MIT - so one license for all the code. The docs will stay at CC, since a code license doesn't make sense.

**Comment by oberstet** [comment]
@thomasgoirand Taken to the extreme: the examples in AutobahnPython would need a dependency on AutobahnJS (and any other JS library used). And to make that explicit (unless I get it wrong .. which might be): a Debian package of AutobahnPython that included the examples would need a dependency on a Debian packaged AutobahnJS. And since AutobahnJS in turn depends on a number of JS libraries, those libraries would need to be Debian packaged as well. And then the docs: to actually be of use to a Debian user, the docs would need to be built. This has a number of additional (Python) dependencies. Which all would need Debian packaging. I think this is crazy. Why all that repackaging when both worlds (Python and JS) each have their (multiple, in case of JS) native packaging systems and repos? Or I just don't get it.

**Comment by thomasgoirand** [comment]
@oberstet 

If we'd need a libjs-autobahn for the examples and doc, then probably the doc would go in a python-autobahn-doc specific package, so that python-autobahn wouldn't have to Depends: on the libjs-autobahn package. Yes, we may need additional Python dependencies, and libjs-* libraries, etc. But you know, that's what we do: we do packages. What you don't get is that we do want everything to be in Debian, self contained, without needing anything not hosted on our repositories. Why? Because most tools like pip or bower are a nightmare, and don't integrate well at all on a distribution. We care having a single package manager, not one per language. Call us crazy for that if you want... (just to be on the safe side: I get what you meant, you wrote that it's a lot of work, and yes it is, but I'm not afraid of such work, I've done this kind of things in the past already).

**Comment by meejah** [comment]
@thomasgoirand I'm working on Autobahn documentation right now. I understand Debian has their own requirements and I completely respect that (and have been a dedicated Debian user for 20+ years). I'm happy to help make AutobahnPython easier for you to package.

Let's wait until my upcoming pull-request improving documentation lands, and if more work is required to meet Debian requirements we can go from there...? This will include (among others): MIT headers in all examples, removed `autobahn*.js` files, and removed `.swf` files.

**Comment by thomasgoirand** [comment]
@meejah thanks a lot! Please ping me to zigo@debian.org when that is done, and I'll package it up in Debian.

**Comment by meejah** [comment]
Hi @thomasgoirand after the #413 merge these issues should be fixed.
Do let me know if there are additional quirks preventing Debian packaging.
