### ISSUE TITLE
Tox: test different Twisted version

### ISSUE THREAD

**Issue by oberstet** [tavendo/AutobahnPython#443]
We could probably catch more issues encountered by users if we tested using Twisted in different versions. This will multiply the number of tested environments, and we can't test every combinations, but probably:

> but 13.2 (version shipped on OSX 10.10), 15.0, and current, might be a good set.
https://github.com/tavendo/AutobahnPython/issues/442#issuecomment-129149086

**Comment by meejah** [comment]
Debian:
 * jessie (stable): 14.0.2
 * wheezy-backports (backports for oldstable): 13.2.0
 * stretch (testing): 15.2.1 (not sure if this will change before stretch becomes stable?)

wheezy itself is using 12.0.0 but it's probably reasonable to "force" anyone still using wheezy to use wheezy-backports to get 13.2.0 instead...

**Comment by oberstet** [comment]
Buildbot is using the following Twisted versions in their CI:

* 11.1
* 12.1
* 13.0
* latest

https://github.com/buildbot/buildbot/blob/master/.travis.yml

**Comment by meejah** [comment]
What distros etc. use 11.1, and 12.1? (Debian oldstable [wheezy] uses 12.0.0, but as the name implies it's pretty old).

Maybe @tardyp can shed light on why these particlar versions?

**Comment by tardyp** [comment]
We avoid to track which distribution uses what and rather try to support
old versions of our deps as long as it is trivial to maintain.

**Comment by hawkowl** [comment]
Autobahn doesn't fully work on versions before 12.1, because of deficiencies in Twisted's endpoint parsing.

As such, I've picked the following list for #451:
- 12.1, as it's the earliest that all the tests pass on
- 13.2, because wheezy-backports and OSX 10.10 uses
- current
- trunk (to make sure we're aware of future things in Twisted, and for the py33/py34 tests).

The travis matrix takes ~10min, which isn't too unreasonable.

I tried to make the tests pass on earlier versions, but couldn't get it. We certainly won't be able to support before 10.1 (when Endpoints was added), but I don't see much value in supporting before 12.1 anyway.

**Comment by oberstet** [comment]
@tardyp : @hawkowl has extended our testing to 3 Twisted variants: 12.1, 13.2 and trunk. I follow her judgement regarding what's appropriate for us rgd Twisted versions.

Nevertheless, AB formally only requires 11.1 (https://github.com/tavendo/AutobahnPython/blob/master/setup.py#L97) - and we leave it at this for now.

Are you ok with that?

**Comment by tardyp** [comment]
If you can't make your tests pass on 11.1, I think you should update your
setup.py. for the intermediate version of twisted, I think we are good
thanks for this!

Le ven. 14 août 2015 12:02, Tobias Oberstein <notifications@github.com> a
écrit :

**Comment by hawkowl** [comment]
11.1 fails a few tests that make endpoints, so we can either "not support it" (as in the tests dont pass) but allow installation, or mark the tests as "expected failures" and run 11.1 on Travis instead of/as well as 12.1. Of course, we could restrict the older Twisteds to CPython only to prevent combinatorial explosion.

**Comment by oberstet** [comment]
@tardyp just to be sure: you say Buildbot would be fine if AutobahnPython would require at least Twisted 12.1 in setup.py?

**Comment by tardyp** [comment]
We have 11.0 in our setup.py, and autobahn is only required for the nine branch. I'm fine with updating our setup to require 12.1.
@sa2jj @djmitche @jaredgrub any objections?

**Comment by tardyp** [comment]
buildbot discussion: https://github.com/buildbot/buildbot/pull/1817

**Comment by djmitche** [comment]
Agreed
