### ISSUE TITLE
s/camelCase/snake_case/g

### ISSUE THREAD

**Issue by ramnes** [tavendo/AutobahnPython#477]
PEP8 plz :scream:

**Comment by Hilkins** [comment]
:+1:

**Comment by Shir0kamii** [comment]
Where do you saw problems with pep8 ? Being more explicit would be helpful to the maintainers.

**Comment by RaitoBezarius** [comment]
@ramnes: AutobahnPython is PEP8-compliant except for variable naming and long lines.

For more information: https://groups.google.com/forum/?hl=fr#!searchin/autobahnws/PEP8/autobahnws/EMKF4a0aXKI/_wBcjGixXNcJ

**Comment by ramnes** [comment]
> @ramnes: AutobahnPython is PEP8-compliant **except for variable naming and long lines**.

So basically, it's not PEP8-compliant, right?

**Comment by RaitoBezarius** [comment]
@ramnes Short answer, yes.

**Comment by oberstet** [comment]
@ramnes there are hundreads of PEP8 rules .. and AB conforms to all but 2.

**Comment by ramnes** [comment]
Yeah, well, those are the two most important rules of the PEP8 to me (and to a lot of developers). I won't argue on why they are important, the PEP8 is there for a reason. Why not just following them?

**Comment by oberstet** [comment]
> So basically, it's not PEP8-compliant, right?

This is plan wrong.

> those are the two most important rules of the PEP8 to me (and to a lot of developers)

There are different opinions on that. But we have that discussion .. I'd be ready .. thing is: it'll break user's apps.

**Comment by ramnes** [comment]
The more the project will grow, the more you'll have unhappy Python developers giving some hate like me because of the bad naming convention, so if I were you, I'd really think it would be better to change sooner than later.

**Comment by oberstet** [comment]
@ramnes I can follow that thinking. if any, now (<1.0) is the time to break stuff https://github.com/tavendo/AutobahnPython/issues/463

**Comment by ramnes** [comment]
That's it.

**Comment by oberstet** [comment]
related: https://github.com/tavendo/AutobahnPython/issues/463

**Comment by hawkowl** [comment]
It's worth noting that changing some sections of Autobahn (the Twisted portion, for example) to snake case actually breaks PEP8 (due to this section: https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds). Consistency with the framework it's written against (first Twisted, now Twisted and asyncio) is better than consistency with the default PEP8 rules.

A *truly* PEP8 compliant Autobahn|Python would use snake_case when interfacing with asyncio (eg. ``on_join()``), and camelCase when interfacing with Twisted (eg. ``onJoin()``). PEP8 is about readability, and that section says that the default rules should not apply when:

> When applying the guideline would make the code less readable, even for someone who is used to reading code that follows this PEP. 

That is -- a Twisted user using Autobahn would find it less readable to call a snake_case API, as an asyncio user using Autobahn would find it less readable to call a camelCase API.

**Comment by hawkowl** [comment]
(however the long lines are a problem to be fixed, Twisted and PEP8 are 79 characters. That being said, PEP8 says 72 characters for docstrings, and Twisted says 79. I'm not sure why they have reason to be different, and I'm nearly certain that Twisted's is better.)

**Comment by oberstet** [comment]
@hawkowl this is interesting. I didn't knew about this rule. that makes it even more complicated for us, since a goal of AB is to make it possible to write user code that is source compatible over tx and asyncio. it's even more of a problem with https://github.com/tavendo/txaio, as we definitely MUST have a single API on that (as we are using it in AB to make single-source over tx/aio possible)

**Comment by ramnes** [comment]
@hawkowl You're entirely right. But as you just told, Autobahn deals with multiple libraries written with different rules, so rather than choosing one to follow randomly, I would rather choose the official Python rules.

**Comment by oberstet** [comment]
> so rather than choosing one to follow randomly,

I think what @hawkowl ment is: have PEP8 on the asyncio API of AB, and tx standards on the tx flavor of AB's API ..

**Comment by hawkowl** [comment]
@oberstet One possible solution would be to have a canonical API (which is PEP8 default snake_case), and then the Twisted ones expose a Twisted-style API (therefore making users codebases consistent, and making PEP8 happy).

In this case -- internal Autobahn is completely reasonable to make uniformly snake_case -- but then we selectively expose APIs which match the target platform. txaio is not a public interface in Autobahn, so it remains snake case.

**Comment by ramnes** [comment]
The voice of Truth.

**Comment by oberstet** [comment]
we're gonna address that. pls see https://github.com/tavendo/AutobahnPython/issues/496
