### ISSUE TITLE
Add header before connect with crossbar

### ISSUE THREAD

**Issue by Budulianin** [tavendo/AutobahnPython#478]
Hi

I'm searching opportunity add header with token before wamp app connect to crossbar.
I want to receive this header with token in authorizer app that run in crossbar for check.
At the moment I didn't find solution.
Where do I add own header so what received it in authorizer app with another headers?

`def authorize(self, session, uri, action)`
E.g. header with token will be in session['http_headers_received']

**Comment by oberstet** [comment]
note: we have a mailing list to ask questions;) this is an _issue_ tracker. and it isn't for crossbar.

https://groups.google.com/forum/#!forum/autobahnws
https://groups.google.com/forum/#!forum/crossbario

answer: you can get transport level details for a WAMP session ID via the meta API in Crossbar.io: http://crossbar.io/docs/Session-Metaevents-and-Procedures/#procedures

=> `wamp.session.get`

having said that, if you need that in an authorizer (rather than authenticator) you are doing it wrong.

the HTTP header should influence under what `authrole` the session is authenticator (=> dynamic authenticators).

the authorizer should only rely on `authrole` and `URI` and `action` to determine if that is allowed or not.

**Comment by Budulianin** [comment]
I'm sorry about that wrote here.

But I wanted know how set header for wamp connection. So this header will be there

`{'realm': u'realm1', ... 'transport': {'peer': 'tcp4:127.0.0.1:53469', 'protocol': 'wamp.2.json.batched', ... 'http_headers_received': {u'upgrade': u'WebSocket',u'host': u'localhost:6060', u'pragma': u'no-cache', u'cache-control': u'no-cache'}}`

This from session dict in authorize(self, session, uri, action)

It is possible? Or need to climb under hood autobahn ?

**Comment by oberstet** [comment]
Setting custom HTTP headers for a client is possible at the WebSocket  level, but not exposed at the WAMP level.

**Comment by Budulianin** [comment]
Is it mean that I need to override autobahn.twisted.wamp.ApplicationSession?

**Comment by oberstet** [comment]
SO is dead. whatever. no, you would need to dig quite deep into Autobahn. lets put it like this: it's simply not supported. period.

**Comment by Budulianin** [comment]
It's strange and inconveniently that need to climb so deep dig for set header.
If I will make pull request with feature that can set header on wamp level, do you merge it?

**Comment by oberstet** [comment]
Before you put any work into this, the best would be to file a issue with a feature request and describe your **use case**. What do you want to achieve? Why do you want to do that? I am not convinced there is a valid use case. But I might be wrong of course / change my mind when your use case and argumentation is compelling. But this needs discussion. Without that, I likely won't merge a PR .. and that would mean wasted time on your side.

**Comment by Budulianin** [comment]
Ok, I'm going to create issue soon about that. Please give me prompt about
 "Or maybe can possible pass some information in wamp session? So that it was available(authorize(self, session, uri, action)) How can pass information from client app to authorizer ?"
