### ISSUE TITLE
When the operation has been completed, I should be how to end job?

### ISSUE THREAD

**Issue by shellus** [tavendo/AutobahnPython#527]
```
#coding=utf-8
__author__ = 'shellus'

from twisted.internet.defer import returnValue
from autobahn.twisted.wamp import Application
import sys


app = Application(u'com.example')


@app.register()
def add2(a, b):
    print("add2() called")
    return a + b


@app.register(u'com.example.hello')
def hello():
    print("hello() called")
    res = yield app.session.call(u'com.example.add2', 2, 3)
    returnValue("Hello {}".format(res))


@app.signal('onjoined')
def onjoined():
    app.session.publish(u'com.example.notice', sys.argv[1])
    # the stop code!



if __name__ == "__main__":
    app.run(u"ws://127.0.0.1:8080/ws", u"realm1")


```

ctrl + c is not elegant

**Comment by shellus** [comment]
```
#coding=utf-8
__author__ = 'shellus'

from twisted.internet.defer import returnValue
from autobahn.twisted.wamp import Application
import sys
from twisted.internet import reactor

app = Application(u'com.example')


@app.register()
def add2(a, b):
    print("add2() called")
    return a + b


@app.register(u'com.example.hello')
def hello():
    print("hello() called")
    res = yield app.session.call(u'com.example.add2', 2, 3)
    returnValue("Hello {}".format(res))


@app.signal('onjoined')
def onjoined():
    app.session.publish(u'com.example.notice', sys.argv[1])
    # the stop code!
    reactor.stop()



if __name__ == "__main__":
    app.run(u"ws://127.0.0.1:8080/ws", u"realm1")


```
I now use reactor.stop () to achieve。
This is the recommended approach it?

**Comment by meejah** [comment]
We are working on an improved API for running things (which will include arranging for the event-loop to terminate).

Using Twisted, you do have to arrange for ``reactor.stop()`` to get called precisely once. So, the short answer above is: yes, you need to call .stop() when you're done. You probably want to call ``.leave()`` first though.

There is ``twisted.internet.task.react`` for "client-type" things (this calls .run and .stop for you). In Autobahn, there is one of the ``ApplicationRunner`` classes (autobahn.twisted.wamp.ApplicationRunner, e.g.) which can "run" an ``ApplicationSession`` subclass. This will call ``.stop`` on (fatal) errors, but otherwise you still need to arrange for ``.stop`` to get called if you're finished.

p.s. this is a bug-tracker; pure questions are best asked on IRC (freenode) in #autobahn or on the mailing-list
